### ISSUE TITLE
Failing migration with Postgres

### ISSUE THREAD

**Issue by mbehrle** [mayan-edms/mayan-edms#127]
(x86_64)[mayan_10]mathiasb@obelix:~/projects/mayan_10/mayan/mayan$ bin/mayan-edms-test.py test
converter.office_converter <26776> [DEBUG] "__init__() self.libreoffice_path: /usr/bin/libreoffice"
ocr.parsers <26776> [DEBUG] "__init__() self.pdftotext_path: /usr/bin/pdftotext"
Creating test database for alias 'default'...
FATAL ERROR - The following SQL query failed: ALTER TABLE "acls_accessentry" ADD CONSTRAINT "permission_id_refs_id_6f1e27ee" FOREIGN KEY ("permission_id") REFERENCES "permissions_storedpermission" ("id") DEFERRABLE INITIALLY DEFERRED;
The error was: FEHLER:  Relation »permissions_storedpermission« existiert nicht

Error in migration: acls:0001_initial
Traceback (most recent call last):
  File "bin/mayan-edms-test.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 50, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 71, in execute
    super(Command, self).execute(*args, **options)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/south/management/commands/test.py", line 8, in handle
    super(Command, self).handle(*args, **kwargs)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 88, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/django/test/runner.py", line 145, in run_tests
    old_config = self.setup_databases()
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/django/test/runner.py", line 107, in setup_databases
    return setup_databases(self.verbosity, self.interactive, **kwargs)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/django/test/runner.py", line 279, in setup_databases
    verbosity, autoclobber=not interactive)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/south/hacks/django_1_0.py", line 103, in wrapper
    return f(*args, **kwargs)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/django/db/backends/creation.py", line 339, in create_test_db
    load_initial_data=False)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/south/management/commands/syncdb.py", line 103, in handle_noargs
    management.call_command('migrate', **options)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/south/migration/migrators.py", line 331, in migrate_many
    result = self.migrate(migration, database)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/south/migration/migrators.py", line 85, in run_migration
    south.db.db.execute_deferred_sql()
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/south/db/generic.py", line 318, in execute_deferred_sql
    self.execute(sql)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/south/db/generic.py", line 282, in execute
    cursor.execute(sql, params)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: FEHLER:  Relation »permissions_storedpermission« existiert nicht

**Comment by rosarior** [comment]
Anyway we could automate testing against different DB backends using Travis?

**Comment by rosarior** [comment]
Updated Travis CI config file, Mayan is now tested agains MySQL, Postgres and SQLite

![screenshot from 2015-01-05 04 14 52](https://cloud.githubusercontent.com/assets/413955/5610660/7f68822a-9491-11e4-8d15-fd6b40e148a9.png)

**Comment by rosarior** [comment]
Postgres is more strict during migrations, some fixes: 9474c5306fe3bb09127238c7e56f2cbb4bb937cd

**Comment by rosarior** [comment]
As of dc5de591522b0d6f8ae3003f9e282692b27d3eb6 all tests are building and running A-OK on SQLite, MySQL and Postgres. Please test to close.

![screenshot from 2015-01-05 04 56 45](https://cloud.githubusercontent.com/assets/413955/5611048/4f014a12-9497-11e4-927d-a386cf1752b0.png)

**Comment by mbehrle** [comment]
* Roberto Rosario: " Re: [mayan-edms] Failing migration with Postgres
  (#127)" (Mon, 05 Jan 2015 00:58:23 -0800):

> As of dc5de591522b0d6f8ae3003f9e282692b27d3eb6 all tests are building and
> running A-OK on SQLite, MySQL and Postgres. Please test to close.
> 

Thx a lot! Will test ASAP!

-- 

    Mathias Behrle
    PGP/GnuPG key availabable from any keyserver, ID: 0x8405BBF6

**Comment by mbehrle** [comment]
* Roberto Rosario: " Re: [mayan-edms] Failing migration with Postgres
  (#127)" (Mon, 05 Jan 2015 00:58:23 -0800):

> As of dc5de591522b0d6f8ae3003f9e282692b27d3eb6 all tests are building and
> running A-OK on SQLite, MySQL and Postgres. Please test to close.

After a small fix [0]  I was able to create a new initial database with
initialsetup for sqlite and postgres, that before were failing with

...
  File
"/home/mathiasb/projects/mayan_dev/mayan/mayan/apps/tags/south_migrations/0003_remove_taggit.py",
line 19, in forwards for tag in TaggitModel.objects.all(): File
"/home/mathiasb/.virtualenvs/mayan_dev/local/lib/python2.7/site-packages/django/db/models/query.py",
line 96, in __iter__ self._fetch_all() File
"/home/mathiasb/.virtualenvs/mayan_dev/local/lib/python2.7/site-packages/django/db/models/query.py",
line 857, in _fetch_all self._result_cache = list(self.iterator()) File
"/home/mathiasb/.virtualenvs/mayan_dev/local/lib/python2.7/site-packages/django/db/models/query.py",
line 220, in iterator for row in compiler.results_iter(): File
"/home/mathiasb/.virtualenvs/mayan_dev/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py",
line 713, in results_iter for rows in self.execute_sql(MULTI): File
"/home/mathiasb/.virtualenvs/mayan_dev/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py",
line 786, in execute_sql cursor.execute(sql, params) File
"/home/mathiasb/.virtualenvs/mayan_dev/local/lib/python2.7/site-packages/django/db/backends/util.py",
line 69, in execute return super(CursorDebugWrapper, self).execute(sql, params)
File
"/home/mathiasb/.virtualenvs/mayan_dev/local/lib/python2.7/site-packages/django/db/backends/util.py",
line 53, in execute return self.cursor.execute(sql, params) File
"/home/mathiasb/.virtualenvs/mayan_dev/local/lib/python2.7/site-packages/django/db/utils.py",
line 99, in __exit__ six.reraise(dj_exc_type, dj_exc_value, traceback) File
"/home/mathiasb/.virtualenvs/mayan_dev/local/lib/python2.7/site-packages/django/db/backends/util.py",
line 53, in execute return self.cursor.execute(sql, params) File
"/home/mathiasb/.virtualenvs/mayan_dev/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py",
line 452, in execute return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: taggit_tag


Then I ran the test suites, where one was failing on postgres (not sqlite):

======================================================================
FAIL: test_document_type_views
(documents.tests.DocumentsViewsFunctionalTestCase)
----------------------------------------------------------------------
Traceback (most recent call last): File
"/home/mathiasb/projects/mayan_dev/mayan/mayan/apps/documents/tests.py", line
210, in test_document_type_views self.assertTrue('Document type edited
successfully' in response.content) AssertionError: False is not true

----------------------------------------------------------------------
Ran 25 tests in 243.255s

Looking into that and further testing the migration of an old database tomorrow.

Thx!

[0] https://github.com/mayan-edms/mayan-edms/pull/132


-- 

    Mathias Behrle
    PGP/GnuPG key availabable from any keyserver, ID: 0x8405BBF6

**Comment by rosarior** [comment]
Merged the patch and closing, will investigate the failing test. Thanks!
