### ISSUE TITLE
Thumbnail creation for ods crashing

### ISSUE THREAD

**Issue by mbehrle** [mayan-edms/mayan-edms#140]
Only for ods documents:

[2015-01-13 13:10:58,638: ERROR/MainProcess] Task documents.tasks.task_get_document_image[3d9b5aab-3439-4610-a60d-5aa89b2ccfb1] raised unexpected: UnknownFileFormat()
Traceback (most recent call last):
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/mathiasb/projects/mayan_10/mayan/mayan/apps/documents/tasks.py", line 22, in task_get_document_image
    raise self.retry(exc=exception)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/celery/app/task.py", line 660, in retry
    maybe_reraise()
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/celery/utils/__init__.py", line 242, in maybe_reraise
    reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/home/mathiasb/projects/mayan_10/mayan/mayan/apps/documents/tasks.py", line 20, in task_get_document_image
    return document.get_image(*args, **kwargs)
  File "/home/mathiasb/projects/mayan_10/mayan/mayan/apps/documents/models.py", line 161, in get_image
    file_path = self.get_valid_image(size=size, page=page, zoom=zoom, rotation=rotation, version=version)
  File "/home/mathiasb/projects/mayan_10/mayan/mayan/apps/documents/models.py", line 146, in get_valid_image
    image_cache_name = self.get_image_cache_name(page=page, version=version)
  File "/home/mathiasb/projects/mayan_10/mayan/mayan/apps/documents/models.py", line 141, in get_image_cache_name
    return convert(input_filepath=document_file, output_filepath=cache_file_path, page=page, transformations=transformations, mimetype=self.file_mimetype)
  File "/home/mathiasb/projects/mayan_10/mayan/mayan/apps/converter/api.py", line 95, in convert
    backend.convert_file(input_filepath=input_filepath, output_filepath=output_filepath, transformations=transformations, page=page, file_format=file_format, mimetype=mimetype)
  File "/home/mathiasb/projects/mayan_10/mayan/mayan/apps/converter/backends/graphicsmagick.py", line 80, in convert_file
    raise UnknownFileFormat
UnknownFileFormat

**Comment by mbehrle** [comment]
Running the failed command directly:
mathiasb@monsterix:/tmp$ /usr/bin/gm convert -density 120 /tmp/6ff6fd1043f9d842315d6defeb52a45049c7119929ce1c54676ab1eba05d4c85[0] -quality 85 jpeg:/home/mathiasb/projects/mayan_10/mayan/mayan/media/image_cache/88028069ca15ed098175b76c6dfb6d56ce74ee44bcd5f6d33d04d8b16e4c54f0
/usr/bin/gm convert: Not a JPEG file: starts with 0x50 0x4b (/tmp/6ff6fd1043f9d842315d6defeb52a45049c7119929ce1c54676ab1eba05d4c85).

**Comment by mbehrle** [comment]
It is also not for all ods documents, but for a single one I have here. This one says in OCR document mimetype application/zip instead of correctly application/vnd.oasis.opendocument.spreadsheet.
Will check further.

**Comment by rosarior** [comment]
python-magic is used to detect the mimetype of documents, which itself is a Python wrapper for libmagic. The output of python-magic is used as-is. Try the command:

  file -i <ods document>

to see how libfile is detecting it.

**Comment by mbehrle** [comment]
file returns "Zip archive data, at least v2.0 to extract" for this document. The document opens without problems in libreoffice calc. After saving again from libreoffice file returns in "OpenDocument Spreadsheet".

Very strange, how this can/could happen. Certainly not an issue, that can behandled by Mayan.
