### ISSUE TITLE
south migration with postgres:  tags: 0002_auto__add_tag__chg_field_tagproperties_tag

### ISSUE THREAD

**Issue by mbehrle** [mayan-edms/mayan-edms#154]
Table tags.tag doesn't have the necessary ids to create the foreign key:

```
Running migrations for tags:
 - Migrating forwards to 0006_auto__del_tagproperties.
 > tags:0002_auto__add_tag__chg_field_tagproperties_tag
   = CREATE TABLE "tags_tag" ("id" serial NOT NULL PRIMARY KEY, "label" varchar(128) NOT NULL, "color" varchar(3) NOT NULL) []
   = CREATE TABLE "tags_tag_document" ("id" serial NOT NULL PRIMARY KEY, "tag_id" integer NOT NULL, "document_id" integer NOT NULL) []
   = ALTER TABLE "tags_tag_document" ADD CONSTRAINT "tags_tag_document_tag_id_4db4842983f3005f_uniq" UNIQUE ("tag_id", "document_id") []
   = 
                SELECT kc.constraint_name, kc.column_name, c.constraint_type
                FROM information_schema.constraint_column_usage AS kc
                JOIN information_schema.table_constraints AS c ON
                    kc.table_schema = c.table_schema AND
                    kc.table_name = c.table_name AND
                    kc.constraint_name = c.constraint_name
                WHERE
                    kc.table_schema = %s AND
                    kc.table_name = %s
             ['public', u'tags_tagproperties']
   = 
                SELECT kc.constraint_name, kc.column_name, c.constraint_type
                FROM information_schema.key_column_usage AS kc
                JOIN information_schema.table_constraints AS c ON
                    kc.table_schema = c.table_schema AND
                    kc.table_name = c.table_name AND
                    kc.constraint_name = c.constraint_name
                WHERE
                    kc.table_schema = %s AND
                    kc.table_name = %s
             ['public', u'tags_tagproperties']
   = 
                SELECT kc.constraint_name, kc.column_name, c.constraint_type
                FROM information_schema.constraint_column_usage AS kc
                JOIN information_schema.table_constraints AS c ON
                    kc.table_schema = c.table_schema AND
                    kc.table_name = c.table_name AND
                    kc.constraint_name = c.constraint_name
                WHERE
                    kc.table_schema = %s AND
                    kc.table_name = %s
             ['public', u'tags_tagproperties']
   = 
                SELECT kc.constraint_name, kc.column_name, c.constraint_type
                FROM information_schema.key_column_usage AS kc
                JOIN information_schema.table_constraints AS c ON
                    kc.table_schema = c.table_schema AND
                    kc.table_name = c.table_name AND
                    kc.constraint_name = c.constraint_name
                WHERE
                    kc.table_schema = %s AND
                    kc.table_name = %s
             ['public', u'tags_tagproperties']
   = ALTER TABLE "tags_tagproperties" DROP CONSTRAINT "tags_tagproperties_tag_id_fkey" []
   = ALTER TABLE "tags_tagproperties" ALTER COLUMN "tag_id" TYPE integer, ALTER COLUMN "tag_id" SET NOT NULL, ALTER COLUMN "tag_id" DROP DEFAULT; []
   = ALTER TABLE "tags_tagproperties" ADD CONSTRAINT "tag_id_refs_id_89825299" FOREIGN KEY ("tag_id") REFERENCES "tags_tag" ("id") DEFERRABLE INITIALLY DEFERRED; []
FATAL ERROR - The following SQL query failed: ALTER TABLE "tags_tagproperties" ADD CONSTRAINT "tag_id_refs_id_89825299" FOREIGN KEY ("tag_id") REFERENCES "tags_tag" ("id") DEFERRABLE INITIALLY DEFERRED;
The error was: FEHLER:  Einfügen oder Aktualisieren in Tabelle „tags_tagproperties“ verletzt Fremdschlüssel-Constraint „tag_id_refs_id_89825299“
DETAIL:  Schlüssel (tag_id)=(1) ist nicht in Tabelle „tags_tag“ vorhanden.

Error in migration: tags:0002_auto__add_tag__chg_field_tagproperties_tag
 - Sending post_syncdb signal for tags: ['Tag']
Traceback (most recent call last):
  File "bin/mayan-edms-mbs.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/south/migration/migrators.py", line 256, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/south/migration/migrators.py", line 331, in migrate_many
    result = self.migrate(migration, database)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/south/migration/migrators.py", line 84, in run_migration
    migration_function()
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/south/migration/migrators.py", line 60, in <lambda>
    return (lambda: direction(orm))
  File "/home/mathiasb/projects/mayan_10/mayan/mayan/apps/tags/south_migrations/0002_auto__add_tag__chg_field_tagproperties_tag.py", line 28, in forwards
    db.alter_column(u'tags_tagproperties', 'tag_id', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['tags.Tag']))
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/south/db/generic.py", line 47, in _cache_clear
    return func(self, table, *args, **opts)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/south/db/generic.py", line 555, in alter_column
    field.rel.to._meta.get_field(field.rel.field_name).column
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/south/db/generic.py", line 282, in execute
    cursor.execute(sql, params)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/mathiasb/.virtualenvs/mayan_10/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: FEHLER:  Einfügen oder Aktualisieren in Tabelle „tags_tagproperties“ verletzt Fremdschlüssel-Constraint „tag_id_refs_id_89825299“
DETAIL:  Schlüssel (tag_id)=(1) ist nicht in Tabelle „tags_tag“ vorhanden.
```

**Comment by mbehrle** [comment]
Following migrations for app tags are failing, too (as expected). The remaining apps are migrating cleanly.

**Comment by mbehrle** [comment]
Unchanged so far. Wondering if this could be caused by having defined tags, but no document is tagged in the database.

**Comment by rosarior** [comment]
Managed to trigger the bug! :)

![screenshot from 2015-02-10 04 02 54](https://cloud.githubusercontent.com/assets/413955/6123501/e44e361c-b0d9-11e4-8d21-e1d2bf2154de.png)

**Comment by rosarior** [comment]
The creation of the foreign key (tags_tagproperties.tag model field == tags_tagproperties.tag_id db field) fails, because the table where the foreign key is located (apps.tags.tag) doesn't exists yet. The table for the apps.tags.tag model are created in the same transaction which has not been committed yet because the program hasn't left the "forwards(self, orm)" scope yet.

**Comment by rosarior** [comment]
Solutions:

- have two different transactions
- split the migrations into two
- not point tags_tagproperties.tag to tag_id since that table get deleted in migrations 0006 before its only attribute (color) gets transferred to the new tag model in migration 0003.

**Comment by rosarior** [comment]
Please verify on your copy. I tested against 1.0 -> 1.1 migration w/ Postgres and new installs of 1.1 with Postgres and SQLite. Travis didn't complained (then again it never did).

**Comment by mbehrle** [comment]
* Roberto Rosario: " Re: [mayan-edms] south migration with postgres:  tags:
  0002_auto__add_tag__chg_field_tagproperties_tag (#154)" (Tue, 10 Feb 2015
  01:20:27 -0800):

> Please verify on your copy. I tested against 1.0 -> 1.1 migration w/ Postgres
> and new installs of 1.1 with Postgres and SQLite. Travis didn't complained
> (then again it never did).

Migration runs fine on my old postgres production database from 1.1! So this
last release critical bug is solved!

-- 

    Mathias Behrle
    PGP/GnuPG key availabable from any keyserver, ID: 0x8405BBF6

**Comment by mbehrle** [comment]
Luckiliy closing this one.
