### ISSUE TITLE
Error when running initialsetup

### ISSUE THREAD

**Issue by julianofischer** [mayan-edms/mayan-edms#167]
I got the following error when running initialsetup.
I'm using Ubuntu Gnome 14.04.2 and installed mayan through pip.

'''
Traceback (most recent call last):
  File "/home/juliano/workspace/venvs/mayan/bin/mayan-edms.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/django/core/management/base.py", line 280, in execute
    translation.activate('en-us')
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 130, in activate
    return _trans.activate(language)
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 188, in activate
    _active.value = translation(language)
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 177, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 159, in _fetch
    app = import_module(appname)
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/mayan/apps/tags/__init__.py", line 7, in <module>
    from documents.models import Document
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/mayan/apps/documents/__init__.py", line 10, in <module>
    from dynamic_search.classes import SearchModel
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/mayan/apps/dynamic_search/__init__.py", line 11, in <module>
    APIEndPoint('search', app_name='dynamic_search')
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/mayan/apps/rest_api/classes.py", line 27, in __init__
    api_urls = load_backend('{0}.urls.api_urls'.format(app_name or name))
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/mayan/apps/common/utils.py", line 238, in load_backend
    return getattr(import_module(module_name), klass)
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/mayan/apps/dynamic_search/urls.py", line 5, in <module>
    from .api_views import (
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/mayan/apps/dynamic_search/api_views.py", line 9, in <module>
    from .models import RecentSearch
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/mayan/apps/dynamic_search/models.py", line 15, in <module>
    class RecentSearch(models.Model):
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/mayan/apps/dynamic_search/models.py", line 19, in RecentSearch
    user = models.ForeignKey(User, verbose_name=_('User'), editable=True)
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 76, in ugettext
    return _trans.ugettext(message)
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 281, in ugettext
    return do_translate(message, 'ugettext')
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 263, in do_translate
    _default = translation(settings.LANGUAGE_CODE)
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 177, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 159, in _fetch
    app = import_module(appname)
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/mayan/apps/sources/__init__.py", line 7, in <module>
    from documents.models import Document
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/mayan/apps/documents/models.py", line 589, in <module>
    registry.register(Document)
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/actstream/registry.py", line 85, in register
    self[model_class] = setup_generic_relations(model_class)
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/actstream/registry.py", line 19, in setup_generic_relations
    Action = get_model('actstream', 'action')
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/django/db/models/loading.py", line 271, in get_model
    self._populate()
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name, True)
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/django/db/models/loading.py", line 97, in load_app
    app_module = import_module(app_name)
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/djcelery/__init__.py", line 22, in <module>
    from celery import current_app as celery  # noqa
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/celery/__init__.py", line 130, in <module>
    from celery import five
  File "/home/juliano/workspace/venvs/mayan/local/lib/python2.7/site-packages/celery/five.py", line 51, in <module>
    from kombu.five import monotonic
ImportError: No module named kombu.five
'''

**Comment by julianofischer** [comment]
After installing kombu via pip, I got: ImportError: No module named billiard.exceptions
After installing billiard via pip I got: ImportError: No module named appconf
After installing django-appconf the installation was successfully finished.

**Comment by rosarior** [comment]
Kombu and django-appconf should have installed on it's own, this the initial pip install got interrupted? Interrupted pip install sometimes remain in a state that cannot be resumed and require the deletion of the virtualenv and a restart of the process.

**Comment by rosarior** [comment]
Did your install worked properly afterwards?
