### ISSUE TITLE
error on initialsetup: GPG initialization error

### ISSUE THREAD

**Issue by pycal** [mayan-edms/mayan-edms#168]
Hey, I'm trying to take this for a test drive and I'm getting the following error:

~/.virtualenvs/dms » mayan-edms.py initialsetup
No handlers could be found for logger "converter.runtime"
Traceback (most recent call last):
  File "/Users/myuser/.virtualenvs/dms/bin/mayan-edms.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/core/management/base.py", line 280, in execute
    translation.activate('en-us')
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 130, in activate
    return _trans.activate(language)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 188, in activate
    _active.value = translation(language)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 177, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 159, in _fetch
    app = import_module(appname)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/tags/__init__.py", line 7, in <module>
    from documents.models import Document
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/documents/__init__.py", line 10, in <module>
    from dynamic_search.classes import SearchModel
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/dynamic_search/__init__.py", line 11, in <module>
    APIEndPoint('search', app_name='dynamic_search')
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/rest_api/classes.py", line 27, in __init__
    api_urls = load_backend('{0}.urls.api_urls'.format(app_name or name))
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/common/utils.py", line 238, in load_backend
    return getattr(import_module(module_name), klass)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/dynamic_search/urls.py", line 5, in <module>
    from .api_views import (
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/dynamic_search/api_views.py", line 9, in <module>
    from .models import RecentSearch
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/dynamic_search/models.py", line 15, in <module>
    class RecentSearch(models.Model):
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/dynamic_search/models.py", line 19, in RecentSearch
    user = models.ForeignKey(User, verbose_name=_('User'), editable=True)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 76, in ugettext
    return _trans.ugettext(message)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 281, in ugettext
    return do_translate(message, 'ugettext')
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 263, in do_translate
    _default = translation(settings.LANGUAGE_CODE)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 177, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 159, in _fetch
    app = import_module(appname)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/sources/__init__.py", line 7, in <module>
    from documents.models import Document
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/documents/models.py", line 589, in <module>
    registry.register(Document)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/actstream/registry.py", line 85, in register
    self[model_class] = setup_generic_relations(model_class)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/actstream/registry.py", line 19, in setup_generic_relations
    Action = get_model('actstream', 'action')
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/db/models/loading.py", line 271, in get_model
    self._populate()
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name, True)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/user_management/models.py", line 6, in <module>
    registry.register(User)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/actstream/registry.py", line 85, in register
    self[model_class] = setup_generic_relations(model_class)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/actstream/registry.py", line 19, in setup_generic_relations
    Action = get_model('actstream', 'action')
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/db/models/loading.py", line 271, in get_model
    self._populate()
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name, True)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/db/models/loading.py", line 97, in load_app
    app_module = import_module(app_name)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/document_indexing/__init__.py", line 9, in <module>
    from metadata.models import DocumentMetadata
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/metadata/__init__.py", line 90, in <module>
    APIEndPoint('metadata')
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/rest_api/classes.py", line 27, in __init__
    api_urls = load_backend('{0}.urls.api_urls'.format(app_name or name))
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/common/utils.py", line 238, in load_backend
    return getattr(import_module(module_name), klass)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/metadata/urls.py", line 5, in <module>
    from .api_views import (
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/metadata/api_views.py", line 25, in <module>
    from .serializers import (
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/metadata/serializers.py", line 30, in <module>
    class DocumentNewMetadataSerializer(serializers.Serializer):
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/metadata/serializers.py", line 31, in DocumentNewMetadataSerializer
    metadata_type = serializers.IntegerField(help_text=_('Primary key of the metadata type to be added.'))
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/rest_framework/fields.py", line 826, in __init__
    super(IntegerField, self).__init__(*args, **kwargs)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/rest_framework/fields.py", line 272, in __init__
    super(WritableField, self).__init__(source=source, label=label, help_text=help_text)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/rest_framework/fields.py", line 146, in __init__
    self.help_text = strip_multiple_choice_msg(smart_text(help_text))
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/rest_framework/fields.py", line 116, in strip_multiple_choice_msg
    multiple_choice_msg = force_text(multiple_choice_msg)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/encoding.py", line 100, in force_text
    s = s.__unicode__()
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/functional.py", line 138, in __text_cast
    return func(*self.__args, **self.__kw)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 76, in ugettext
    return _trans.ugettext(message)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 281, in ugettext
    return do_translate(message, 'ugettext')
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 263, in do_translate
    _default = translation(settings.LANGUAGE_CODE)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 177, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 159, in _fetch
    app = import_module(appname)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/linking/__init__.py", line 17, in <module>
    from .models import SmartLink, SmartLinkCondition
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/linking/models.py", line 15, in <module>
    class SmartLink(models.Model):
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/linking/models.py", line 17, in SmartLink
    dynamic_title = models.CharField(blank=True, max_length=96, verbose_name=_('Dynamic title'), help_text=ugettext('This expression will be evaluated against the current selected document.'))
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 76, in ugettext
    return _trans.ugettext(message)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 281, in ugettext
    return do_translate(message, 'ugettext')
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 263, in do_translate
    _default = translation(settings.LANGUAGE_CODE)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 177, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 159, in _fetch
    app = import_module(appname)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/folders/__init__.py", line 21, in <module>
    from .models import Folder
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/folders/models.py", line 10, in <module>
    class Folder(models.Model):
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/folders/models.py", line 11, in Folder
    title = models.CharField(max_length=128, verbose_name=_('Title'), db_index=True)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 76, in ugettext
    return _trans.ugettext(message)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 281, in ugettext
    return do_translate(message, 'ugettext')
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 263, in do_translate
    _default = translation(settings.LANGUAGE_CODE)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 177, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 159, in _fetch
    app = import_module(appname)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/document_states/__init__.py", line 12, in <module>
    from .models import (
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/document_states/models.py", line 15, in <module>
    class Workflow(models.Model):
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/document_states/models.py", line 16, in Workflow
    label = models.CharField(max_length=255, unique=True, verbose_name=_('Label'))
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 76, in ugettext
    return _trans.ugettext(message)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 281, in ugettext
    return do_translate(message, 'ugettext')
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 263, in do_translate
    _default = translation(settings.LANGUAGE_CODE)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 177, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 159, in _fetch
    app = import_module(appname)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/document_signatures/__init__.py", line 12, in <module>
    from django_gpg.runtime import gpg
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/django_gpg/runtime.py", line 4, in <module>
    gpg = GPG(binary_path=GPG_PATH, home=GPG_HOME, keyservers=KEYSERVERS)
  File "/Users/myuser/.virtualenvs/dms/lib/python2.7/site-packages/mayan/apps/django_gpg/api.py", line 131, in __init__
    raise GPGException('ERROR: GPG initialization error; %s' % exception)
django_gpg.exceptions.GPGException: ERROR: GPG initialization error; [Errno 2] No such file or directory

**Comment by pycal** [comment]
Just gave this a try on a diff computer: both macs with latest or close to latest updates installed

**Comment by talfouzan** [comment]
I'm on a Mac getting the same error

**Comment by rosarior** [comment]
Seems to be a GPG initialization error. Is the GPG binary properly installed in a place where Mayan can find it (**/usr/bin/gpg** by default)?  Otherwise you'll need to specify the path to the binary with the setting **SIGNATURES_GPG_PATH** in your **mayan/settings/local.py** file.

**Comment by talfouzan** [comment]
Great all works now😎

**Comment by rosarior** [comment]
Is it working for you too @pycal?

**Comment by pycal** [comment]
I just ended up testing with the docker image @rosarior

**Comment by pycal** [comment]
Ok confirmed, it wasn't able to find the GPG binary. I was able to run mayan-edms.py initialsetup by:

1. Installing Mac GPGTools https://gpgtools.org/
2. Modifying SIGNATURES_GPG_PATH to reflect the location of the gpg binary at /usr/local/bin/gpg

**Comment by clickonchris** [comment]
I wanted to offer a slightly easier solution
