### ISSUE TITLE
Thumbnails not generated: ConvertError in Document List and in Document Preview

### ISSUE THREAD

**Issue by yitjob** [mayan-edms/mayan-edms#197]
Thumbnails are aparently not being generated due to an exception in "/mayan/apps/converter/backends/python.py", line 80, in convert_file

Documents are all office documents (doc and xls).
```Python
from PIL import Image
Image.init()
Image.open('/path/to/file')
```

raises *IOError: cannot identify image file*

**Comment by rosarior** [comment]
I've been usable to triage this issue. Any other information you could provide? Could you provide a public document to trigger the issue?

**Comment by yitjob** [comment]
I ran pip install -r requirements.txt and launched mayan-edms.py runserver and I'm affraid that none of the documents I tried were thumbnailed. In the settings page all components like gm are ok (with a check mark). I'm sorry if I'm making some mistake but cannot figure it out.

**Comment by yitjob** [comment]
I'm afraid I've never seen a thumbnail in any version Mayan, even with the contrib/sample_documents as well.
Here is a stack trace:
```Python
Traceback (most recent call last):
  File "/home/mayan/virtualenvs/mayan1.1.1/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 67, in __call__
    return self.application(environ, start_response)
  File "/home/mayan/virtualenvs/mayan1.1.1/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 206, in __call__
    response = self.get_response(request)
  File "/home/mayan/virtualenvs/mayan1.1.1/lib/python2.7/site-packages/django/core/handlers/base.py", line 194, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/mayan/virtualenvs/mayan1.1.1/lib/python2.7/site-packages/django/core/handlers/base.py", line 229, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/mayan/virtualenvs/mayan1.1.1/lib/python2.7/site-packages/django_extensions/management/technical_response.py", line 5, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/home/mayan/virtualenvs/mayan1.1.1/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mayan/virtualenvs/mayan1.1.1/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mayan/virtualenvs/mayan1.1.1/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mayan/virtualenvs/mayan1.1.1/lib/python2.7/site-packages/rest_framework/views.py", line 403, in dispatch
    response = self.handle_exception(exc)
  File "/home/mayan/virtualenvs/mayan1.1.1/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mayan/virtualenvs/mayan1.1.1/lib/python2.7/site-packages/mayan/apps/documents/api_views.py", line 206, in get
    task = task_get_document_image.apply_async(kwargs=dict(document_id=document.pk, size=size, page=page, zoom=zoom, rotation=rotation, as_base64=True, version=version), queue='converter')
  File "/home/mayan/virtualenvs/mayan1.1.1/lib/python2.7/site-packages/celery/app/task.py", line 551, in apply_async
    link=link, link_error=link_error, **options)
  File "/home/mayan/virtualenvs/mayan1.1.1/lib/python2.7/site-packages/celery/app/task.py", line 743, in apply
    request=request, propagate=throw)
  File "/home/mayan/virtualenvs/mayan1.1.1/lib/python2.7/site-packages/celery/app/trace.py", line 355, in eager_trace_task
    uuid, args, kwargs, request)
  File "/home/mayan/virtualenvs/mayan1.1.1/lib/python2.7/site-packages/celery/app/trace.py", line 253, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/home/mayan/virtualenvs/mayan1.1.1/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/mayan/virtualenvs/mayan1.1.1/lib/python2.7/site-packages/mayan/apps/documents/tasks.py", line 20, in task_get_document_image
    return document.get_image(*args, **kwargs)
  File "/home/mayan/virtualenvs/mayan1.1.1/lib/python2.7/site-packages/mayan/apps/documents/models.py", line 161, in get_image
    file_path = self.get_valid_image(size=size, page=page, zoom=zoom, rotation=rotation, version=version)
  File "/home/mayan/virtualenvs/mayan1.1.1/lib/python2.7/site-packages/mayan/apps/documents/models.py", line 150, in get_valid_image
    return convert(input_filepath=image_cache_name, cleanup_files=False, size=size, zoom=zoom, rotation=rotation)
  File "/home/mayan/virtualenvs/mayan1.1.1/lib/python2.7/site-packages/mayan/apps/converter/api.py", line 95, in convert
    backend.convert_file(input_filepath=input_filepath, output_filepath=output_filepath, transformations=transformations, page=page, file_format=file_format, mimetype=mimetype)
  File "/home/mayan/virtualenvs/mayan1.1.1/lib/python2.7/site-packages/mayan/apps/converter/backends/python.py", line 80, in convert_file
    raise ConvertError
ConvertError
