### ISSUE TITLE
Importing .odt file => /tmp/randomfilename.pdf: no such file or directory

### ISSUE THREAD

**Issue by Nihilivin** [mayan-edms/mayan-edms#243]
Hi,
I've installed a brand new Mayan instance on my server, and configuration seems to work well. But now, I try to import my first document: an odt file.
File is never imported. Tailing the logs during import, I see that:

```
documents.managers <30497> [INFO] "check_trash_periods() Checking trash period of document type: Default"
[2016-10-12 22:38:41,553: INFO/Worker-2] Checking trash period of document type: Default
documents.managers <30497> [INFO] "check_trash_periods() Document type: Default, has a no retention delta"
[2016-10-12 22:38:41,554: INFO/Worker-2] Document type: Default, has a no retention delta
documents.managers <30497> [INFO] "check_trash_periods() Checking trash period of document type: Feuille de calcul"
[2016-10-12 22:38:41,555: INFO/Worker-2] Checking trash period of document type: Feuille de calcul
documents.managers <30497> [INFO] "check_trash_periods() Document type: Feuille de calcul, has a no retention delta"
[2016-10-12 22:38:41,556: INFO/Worker-2] Document type: Feuille de calcul, has a no retention delta
documents.managers <30497> [INFO] "check_trash_periods() Finshed"
[2016-10-12 22:38:41,557: INFO/Worker-2] Finshed
documents.models <30496> [INFO] "new_version() Creating new document version for document: ttmp.ods"
[2016-10-12 22:38:54,273: INFO/Worker-1] Creating new document version for document: ttmp.ods
documents.models <30496> [INFO] "save() Creating new version for document: ttmp.ods"
[2016-10-12 22:38:54,275: INFO/Worker-1] Creating new version for document: ttmp.ods
documents.models <30496> [ERROR] "save() Error creating new document version for document "ttmp.ods"; [Errno 2] No such file or directory: u'/tmp/tmpYemKf3.pdf'"
[2016-10-12 22:38:55,922: ERROR/Worker-1] Error creating new document version for document "ttmp.ods"; [Errno 2] No such file or directory: u'/tmp/tmpYemKf3.pdf'
sources.models <30496> [CRITICAL] "upload_document() Unexpected exception while trying to create new document "ttmp.ods" from source "Default"; [Errno 2] No such file or directory: u'/tmp/tmpYemKf3.pdf'"
[2016-10-12 22:38:55,925: CRITICAL/Worker-1] Unexpected exception while trying to create new document "ttmp.ods" from source "Default"; [Errno 2] No such file or directory: u'/tmp/tmpYemKf3.pdf'
[2016-10-12 22:38:55,937: ERROR/MainProcess] Task sources.tasks.task_upload_document[02aa2f60-3a9a-4004-ab4c-4a455caad94d] raised unexpected: IOError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/usr/share/mayan-edms/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/share/mayan-edms/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/share/mayan-edms/lib/python2.7/site-packages/mayan/apps/sources/tasks.py", line 68, in task_upload_document
    tag_ids=tag_ids
  File "/usr/share/mayan-edms/lib/python2.7/site-packages/mayan/apps/sources/models.py", line 74, in upload_document
    file_object=file_object, _user=user
  File "/usr/share/mayan-edms/lib/python2.7/site-packages/mayan/apps/documents/models.py", line 254, in new_version
    document_version.save(_user=_user)
  File "/usr/share/mayan-edms/lib/python2.7/site-packages/mayan/apps/documents/models.py", line 414, in save
    self.update_page_count(save=False)
  File "/usr/share/mayan-edms/lib/python2.7/site-packages/mayan/apps/documents/models.py", line 589, in update_page_count
    detected_pages = converter.get_page_count()
  File "/usr/share/mayan-edms/lib/python2.7/site-packages/mayan/apps/converter/backends/python.py", line 78, in get_page_count
    file_object = IteratorIO(self.soffice_file).file_buffer
  File "/usr/share/mayan-edms/lib/python2.7/site-packages/mayan/apps/converter/backends/python.py", line 39, in __init__
    for chunk in iterator:
  File "/usr/share/mayan-edms/lib/python2.7/site-packages/mayan/apps/converter/classes.py", line 162, in soffice
    with open(converted_output) as converted_file_object:
IOError: [Errno 2] No such file or directory: u'/tmp/tmpYemKf3.pdf'
documents.managers <30497> [INFO] "check_delete_periods() Executing"
[2016-10-12 22:39:41,464: INFO/Worker-2] Executing
documents.managers <30497> [INFO] "check_delete_periods() Checking deletion period of document type: Default"
[2016-10-12 22:39:41,510: INFO/Worker-2] Checking deletion period of document type: Default
documents.managers <30497> [INFO] "check_delete_periods() Document type: Default, has a deletion period delta of: 30 days, 0:00:00"
[2016-10-12 22:39:41,511: INFO/Worker-2] Document type: Default, has a deletion period delta of: 30 days, 0:00:00
documents.managers <30497> [INFO] "check_delete_periods() Checking deletion period of document type: Feuille de calcul"
[2016-10-12 22:39:41,525: INFO/Worker-2] Checking deletion period of document type: Feuille de calcul
documents.managers <30499> [INFO] "check_trash_periods() Executing"
documents.managers <30497> [INFO] "check_delete_periods() Document type: Feuille de calcul, has a deletion period delta of: 30 days, 0:00:00"
[2016-10-12 22:39:41,526: INFO/Worker-2] Document type: Feuille de calcul, has a deletion period delta of: 30 days, 0:00:00
[2016-10-12 22:39:41,526: INFO/Worker-4] Executing
documents.managers <30497> [INFO] "check_delete_periods() Finshed"
```

I don't understand why it looks for a .pdf file, as I'm importing a .odt file.... Can you please provide me some clues to solve this problem?

Thank you

**Comment by rosarior** [comment]
Internally Mayan converts anything non image document into PDF first. It is trying to use LibreOffice to convert the ODT file to a PDF. Make sure LibreOffice is correctly installed and can convert ODT files to PDF using the command line.
